### PR TITLE
OSX testing fixes

### PR DESCRIPTION
**Pull request by AGulev**
Some fixes for testing app on macos

### CODE REVIEW

**Comment by lpmitchell** [comment]
Thanks for the PR @AGulev,

We're testing this internally now, I'll update this PR when it has been tested!

**Comment by AGulev** [comment]
Any news?

**Comment by AGulev** [comment]
@lpmitchell , it's just few changes in code for macos. It's not affect work on mobile devices. 
Without this code I have to to remove defold-connector every time when I want to test game on macOS.

**Comment by lpmitchell** [comment]
Hey AGulev,

Apologies for the delays on this. I'll flag it up again today, it should be implemented very soon.

**Pull request merged**
